debezium.sink.type=rabbitmq

debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=toyboyz
debezium.sink.rabbitmq.connection.password=toyboyz
debezium.sink.rabbitmq.connection.virtual.host=/

# RabbitMQ exchange
debezium.sink.rabbitmq.exchange=outbox.exchange
debezium.sink.rabbitmq.stream.enabled=false
debezium.sink.rabbitmq.exchange.type=topic
debezium.sink.rabbitmq.exchange.auto.delete=false
debezium.sink.rabbitmq.routingKey.source=topic
#debezium.sink.rabbitmq.routingKeyFromTopicName=true

# Source: MySQL
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
#debezium.source.database.hostname=file-conversion-database-1.cn6kiey0qu1a.ap-northeast-2.rds.amazonaws.com
debezium.source.database.hostname=host.docker.internal
debezium.source.database.connectionTimeZone=Asia/Seoul
debezium.source.database.port=3306
#debezium.source.database.user=toyboyz
#debezium.source.database.password=toytoy123
debezium.source.database.user=root
debezium.source.database.password=
debezium.source.database.server.id=5401

debezium.source.topic.prefix=api
debezium.source.database.include.list=api
debezium.source.table.include.list=api.outbox_event

# Offsets / Schema History
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=1000

debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema-history.dat


# SMT: Outbox Event Router
debezium.source.transforms=outbox
debezium.source.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter

# outbox_event
debezium.source.transforms.outbox.table.field.event.id=id
debezium.source.transforms.outbox.table.field.event.key=aggregate_id
debezium.source.transforms.outbox.table.field.event.payload=payload

# routing key = outbox.event.<aggregate_type>
debezium.source.transforms.outbox.route.by.field=aggregate_type
debezium.source.transforms.outbox.route.topic.replacement=outbox.event.$${routedByValue}